### ISSUE TITLE
SAGE-1387 Github workflows template modification

### ISSUE THREAD

**Issue by iperezx** [waggle-sensor/.github#1]
Hard coded value for docker org owner: https://github.com/waggle-sensor/.github/blob/main/workflow-templates/build-and-push-docker-image.yml#L28

If a user tries to fork from any of the waggle repositories and uses the templates in this repo, it will error out. Maybe the intended usage is that a user is only working under waggle-sensor and allowed to push to the waggle Dockerhub account.

One way to change this is to use a github var like the following:
```
        with:
          images: |
            ${{ github.repository_owner }}/${{ github.event.repository.name }}
```

This assumes that the dockerhub account and github account are the same. I am doing this in one of the repos I forked: https://github.com/iperezx/node-platforms. I set up all the Dockerhub secrets in the repository so I can push to my Dockerhub account.

Or we can use a secret variable in github so it will be the same when a user makes a PR to the waggle repo.

**Comment by seanshahkarami** [comment]
I'd really like to do this, but as you pointed out, the main intent is to push images to the Dockerhub `waggle` organization. Unfortunately, our Github organization name is `waggle-sensor`, so they don't match.

**Comment by seanshahkarami** [comment]
Perhaps we can unify this by using a secret (or some variable tied to the repo)?

Something like:
1. If secret like `DOCKER_ORG` exists, use that.
2. Otherwise, default to {repo owner} / {repo name} like you suggested.

**Comment by iperezx** [comment]
Yes that was my second suggestion. We can just provide instructions of how to setup the DOCKER_ORG as a secret and so the workflow template will require minimal changes.

**Comment by seanshahkarami** [comment]
Oh yeah, my bad. I somehow missed that. Yeah, if you can add a conditional for that, I think that's a good approach.
